//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitAspx.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitAspx.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        public static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone the repository using this command.
        /// </summary>
        public static string CloneRepositoryCommand {
            get {
                return ResourceManager.GetString("CloneRepositoryCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        public static string Commit {
            get {
                return ResourceManager.GetString("Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new bare repository.
        /// </summary>
        public static string CreateBareRepository {
            get {
                return ResourceManager.GetString("CreateBareRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a category.
        /// </summary>
        public static string CreateCategory {
            get {
                return ResourceManager.GetString("CreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new repository.
        /// </summary>
        public static string CreateRepository {
            get {
                return ResourceManager.GetString("CreateRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultures.
        /// </summary>
        public static string Cultures {
            get {
                return ResourceManager.GetString("Cultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directories.
        /// </summary>
        public static string Directories {
            get {
                return ResourceManager.GetString("Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide tree node details.
        /// </summary>
        public static string HideTreeNodeDetails {
            get {
                return ResourceManager.GetString("HideTreeNodeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents.
        /// </summary>
        public static string Parents {
            get {
                return ResourceManager.GetString("Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click on the file to download, directory to download as zip.
        /// </summary>
        public static string RightClickToDownload {
            get {
                return ResourceManager.GetString("RightClickToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click on the repository to show git url.
        /// </summary>
        public static string RightClickToShowGitUrl {
            get {
                return ResourceManager.GetString("RightClickToShowGitUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settngs {
            get {
                return ResourceManager.GetString("Settngs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tree node details.
        /// </summary>
        public static string ShowTreeNodeDetails {
            get {
                return ResourceManager.GetString("ShowTreeNodeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
    }
}
